"""
CFFT / CIFFT / RFFT / IRFFT Q31 Test Vector Generator
=======================================================
Generates Q31 fixed-point test data for all FFT variants.

Uses the DspAccumulator-based DIF FFT model that matches the dsPIC33AK
assembly exactly, including sacr.l #1 convergent rounding at each
butterfly stage.

Outputs test input/expected files for the hardware test project.

Author: Generated for cmsis-dsp-mchp Q31 FFT testing
"""

import numpy as np
from helper_q31 import *
from dspic_q31_model import (
    to_signed32, dspic_cfft_q31, bit_reverse_complex_q31,
    dspic_cfft_dif_q31, dspic_rfft_fast_q31, dspic_irfft_fast_q31
)

np.random.seed(42)  # reproducible test vectors

# ============================================================
# Configuration
# ============================================================
N = 128        # FFT length (complex points)
LOG2N = 7      # log2(N)
gSCL = 0.5     # Scale factor (keep < 0.5 to avoid saturation)
gOFF = 0.25    # Offset to center around zero


def generate_twiddle_q31(N):
    """Generate the twiddle factor table matching twiddleCoef_q31_128.
    
    Convention: W(k) = cos(2*pi*k/N) + j*sin(2*pi*k/N), k=0..N-1
    Interleaved as [Wr0, Wi0, Wr1, Wi1, ...]
    """
    twid = []
    for k in range(N):
        wr = np.cos(2.0 * np.pi * k / N)
        wi = np.sin(2.0 * np.pi * k / N)
        twid.append(float_to_q31(wr))
        twid.append(float_to_q31(wi))
    return np.array(twid, dtype=np.int32)


def generate_cfft_test_vectors():
    """Generate CFFT Q31 test vectors using the exact DIF model."""
    
    print("Generating CFFT Q31 test vectors (N=%d)..." % N)
    
    # Generate random input in [-0.25, +0.25) range (< 0.5 magnitude)
    re_in = gSCL * np.random.random_sample(N) - gOFF
    im_in = gSCL * np.random.random_sample(N) - gOFF
    re_in = np.clip(re_in, -1.0, 1.0 - 1.0/(2**31))
    im_in = np.clip(im_in, -1.0, 1.0 - 1.0/(2**31))
    
    # Interleave and convert to Q31
    src = []
    for i in range(N):
        src.append(float_to_q31(re_in[i]))
        src.append(float_to_q31(im_in[i]))
    src_q31 = np.array(src, dtype=np.int32)
    
    # Generate twiddle table
    twid_q31 = generate_twiddle_q31(N)
    
    # Compute expected CFFT output using exact DIF model
    # The assembly does: DIF FFT core + bit reversal
    fft_out = dspic_cfft_q31(src_q31.copy(), twid_q31, N, ifftFlag=0, bitRevFlag=1)
    
    print(f"  Input: {len(src_q31)} Q31 values ({N} complex)")
    print(f"  Output: {len(fft_out)} Q31 values ({N} complex)")
    
    # Verify against numpy IFFT (sanity check).
    # The DIF butterfly with twiddle e^{+j*theta} (cos+j*sin) computes
    # the IDFT kernel, scaled by 1/N from the butterfly stages.
    # So the assembly "forward FFT" output = numpy.ifft(input).
    src_complex = re_in + 1j * im_in
    numpy_ifft = np.fft.ifft(src_complex)
    numpy_ifft_q31 = []
    for c in numpy_ifft:
        numpy_ifft_q31.append(int(float_to_q31(c.real)))
        numpy_ifft_q31.append(int(float_to_q31(c.imag)))
    numpy_ifft_q31 = np.array(numpy_ifft_q31, dtype=np.int32)
    
    # Compare
    diff = np.abs(fft_out.astype(np.int64) - numpy_ifft_q31.astype(np.int64))
    max_diff = int(np.max(diff))
    print(f"  Max diff vs numpy IFFT: {max_diff} (expected small, 1-3 LSB)")
    
    return src_q31, fft_out, twid_q31


def generate_cifft_test_vectors(fft_output_q31, twid_q31):
    """Generate CIFFT Q31 test vectors.
    
    The CIFFT uses the SAME DIF core as the forward FFT.
    Input = FFT output (in natural order).
    The assembly CIFFT path calls the same _FFTComplexIP_noBitRev_q31 core.
    """
    print("Generating CIFFT Q31 test vectors (N=%d)..." % N)
    
    # The CIFFT input is the FFT output
    cifft_input = fft_output_q31.copy()
    
    # CIFFT: same DIF core + bit reversal
    cifft_out = dspic_cfft_q31(cifft_input.copy(), twid_q31, N, ifftFlag=1, bitRevFlag=1)
    
    print(f"  Input: {len(cifft_input)} Q31 values ({N} complex)")
    print(f"  Output: {len(cifft_out)} Q31 values ({N} complex)")
    
    return cifft_input, cifft_out


def format_c_file(test_name, arrays_dict, includes, guards):
    """Format a C test input file with multiple arrays."""
    lines = []
    lines.append("/*")
    lines.append(f" * File:   {test_name}")
    lines.append(f" * Comments: Q31 test vectors for {test_name}")
    lines.append(f" *           Generated by cfft_q31.py")
    lines.append(" * Revision history:")
    lines.append(" */")
    lines.append("")
    for inc in includes:
        lines.append(f'#include "{inc}"')
    lines.append("")
    for guard in guards:
        lines.append(f"#ifdef {guard}")
    lines.append("")
    
    for arr_name, (arr_data, attr) in arrays_dict.items():
        arr = np.asarray(arr_data, dtype=np.int32)
        lines.append(f"q31_t {attr}{arr_name}[] = {{")
        for i in range(0, len(arr), 2):
            vals = []
            for j in range(i, min(i+2, len(arr))):
                uval = int(arr[j]) & 0xFFFFFFFF
                vals.append(f"0x{uval:08X}")
            sep = "," if i + 2 < len(arr) else ""
            lines.append(f"    {', '.join(vals)}{sep}")
        lines.append("};")
        lines.append("")
    
    for guard in reversed(guards):
        lines.append(f"#endif")
    lines.append("")
    return "\n".join(lines)


def generate_rfft_test_vectors(twid_q31):
    """Generate forward RFFT Q31 test vectors using the exact model.
    
    RFFT input: N real Q31 samples.
    RFFT expected output: N+2 Q31 values (N/2+1 complex frequency bins).
    """
    print("Generating RFFT Q31 test vectors (N=%d)..." % N)
    
    # Generate random real input in [-0.25, +0.25) range (< 0.5 magnitude)
    # Use a separate seed so RFFT input differs from CFFT input
    rng_state = np.random.get_state()
    np.random.seed(100)
    real_in = gSCL * np.random.random_sample(N) - gOFF
    real_in = np.clip(real_in, -1.0, 1.0 - 1.0/(2**31))
    np.random.set_state(rng_state)
    
    # Convert to Q31
    src_q31 = np.array([float_to_q31(x) for x in real_in], dtype=np.int32)
    src_list = [int(x) for x in src_q31]
    
    # Compute expected RFFT output using exact model
    rfft_out = dspic_rfft_fast_q31(src_list, twid_q31, N)
    
    # Expected output: first N+2 values (N/2+1 complex bins)
    rfft_expected = rfft_out[:N + 2]
    
    print(f"  Input: {len(src_q31)} Q31 values ({N} real samples)")
    print(f"  Output: {len(rfft_expected)} Q31 values ({N//2+1} complex bins)")
    print(f"  DC:  {to_signed32(int(rfft_expected[0]))/2**31:.6f} + j*{int(rfft_expected[1])}")
    print(f"  Nyq: {to_signed32(int(rfft_expected[N]))/2**31:.6f} + j*{int(rfft_expected[N+1])}")
    
    return src_q31, rfft_expected


def generate_irfft_test_vectors(rfft_output_q31, twid_q31):
    """Generate inverse RFFT Q31 test vectors.
    
    IRFFT input: RFFT output (N+2 values, zero-padded to 2*N for the copy).
    IRFFT expected output: N real Q31 values.
    """
    print("Generating IRFFT Q31 test vectors (N=%d)..." % N)
    
    # The IRFFT input is the RFFT output.
    # The assembly copies 2*N Q31 values from input to output buffer,
    # so the input array should be 2*N values. Pad with zeros.
    irfft_input = np.zeros(2 * N, dtype=np.int32)
    irfft_input[:len(rfft_output_q31)] = rfft_output_q31
    
    irfft_input_list = [int(x) for x in irfft_input]
    
    # Compute expected IRFFT output using exact model
    irfft_out = dspic_irfft_fast_q31(irfft_input_list, twid_q31, N)
    
    # Expected output: first N values (real time-domain samples)
    irfft_expected = irfft_out[:N]
    
    print(f"  Input: {len(irfft_input)} Q31 values (2*N, zero-padded)")
    print(f"  Output: {len(irfft_expected)} Q31 values ({N} real samples)")
    
    return irfft_input, irfft_expected


# ============================================================
# Main
# ============================================================
if __name__ == "__main__":
    # Generate forward CFFT vectors
    src_q31, fft_out_q31, twid_q31 = generate_cfft_test_vectors()
    
    # Generate inverse CIFFT vectors
    cifft_input_q31, cifft_out_q31 = generate_cifft_test_vectors(fft_out_q31, twid_q31)
    
    # Generate forward RFFT vectors
    rfft_src_q31, rfft_expected_q31 = generate_rfft_test_vectors(twid_q31)
    
    # Generate inverse RFFT vectors (using RFFT output as input)
    irfft_input_q31, irfft_expected_q31 = generate_irfft_test_vectors(
        rfft_expected_q31, twid_q31)
    
    # Write CFFT test file
    fft_content = format_c_file(
        "FFT_q31_test_inputs.c",
        {
            "FFT_src1": (src_q31, '__attribute__((space(xmemory))) '),
            "FFT_er": (fft_out_q31, ''),
        },
        ["../../main.h"],
        ["TRANSFORM_LIB_TEST", "DATA_SET_I"],
    )
    replace_test_file("fft_q31_test_inputs", fft_content)
    
    # Write CIFFT test file
    ifft_content = format_c_file(
        "IFFT_q31_test_inputs.c",
        {
            "IFFT_src1": (cifft_input_q31, '__attribute__((space(xmemory))) '),
            "IFFT_er": (cifft_out_q31, ''),
        },
        ["../../main.h"],
        ["TRANSFORM_LIB_TEST", "DATA_SET_I"],
    )
    replace_test_file("ifft_q31_test_inputs", ifft_content)
    
    # Write RFFT test file
    rfft_content = format_c_file(
        "RFFT_q31_test_inputs.c",
        {
            "RFFT_src1": (rfft_src_q31, '__attribute__((space(xmemory))) '),
            "RFFT_er": (rfft_expected_q31, ''),
        },
        ["../../main.h"],
        ["TRANSFORM_LIB_TEST", "DATA_SET_I"],
    )
    replace_test_file("rfft_q31_test_inputs", rfft_content)
    
    # Write IRFFT test file
    # IRFFT_src1 needs 2*N values (assembly copies 2*N). Use the padded version.
    irfft_content = format_c_file(
        "IRFFT_q31_test_inputs.c",
        {
            "IRFFT_src1": (irfft_input_q31, ''),
            "IRFFT_er": (irfft_expected_q31, ''),
        },
        ["../../main.h"],
        ["TRANSFORM_LIB_TEST", "DATA_SET_I"],
    )
    replace_test_file("irfft_q31_test_inputs", irfft_content)
    
    print("\nDone! All test vectors written.")
    print("\nRemember to copy files to C:\\CMSIS\\my_branch\\Testing\\...")
